AllCops:
  TargetRubyVersion: 2.4.1
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'log/**/*'
    - 'integral.gemspec'

Metrics/LineLength:
  Max: 100

Style/FrozenStringLiteralComment:
  Enabled: false
